// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWyUbsJ1pOVHwwtU3Rluol93iJ-mDd8c',
    appId: '1:1033419497693:web:43db75915942699c40fb34',
    messagingSenderId: '1033419497693',
    projectId: 'donskih-push',
    authDomain: 'donskih-push.firebaseapp.com',
    storageBucket: 'donskih-push.firebasestorage.app',
    measurementId: 'G-VM6WTXMMJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA38jGPriZ0m_YV0lc0yW8NXh9c0_L-fCI',
    appId: '1:1033419497693:android:38c2ef8cdf1ed49f40fb34',
    messagingSenderId: '1033419497693',
    projectId: 'donskih-push',
    storageBucket: 'donskih-push.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4l_-E13cwRGpVHypq4-ATYJp5f4UJr7k',
    appId: '1:1033419497693:ios:d426b9ecbf9909e840fb34',
    messagingSenderId: '1033419497693',
    projectId: 'donskih-push',
    storageBucket: 'donskih-push.firebasestorage.app',
    iosBundleId: 'com.club.clubApp',
  );
}
